global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.148:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.148:9100']
